config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [ :index, :show ]

  root 'activities#index'

  get 'lifetime_monthly_mileage' => 'activities#mileage', :as => :activities_mileage

  get 'activity/:id/heart_rate' => 'activities#heart_rate', :as => :heart_rate
  get 'activity/:id/elevation' => 'activities#elevation', :as => :elevation
  get 'activity/:id/speed' => 'activities#speed', :as => :speed
  get 'activity/:id/heart_rate_intensity' => 'activities#heart_rate_intensity', :as => :heart_rate_intensity
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :geo_points
  has_many :laps

  has_attached_file :geo_route, url: '/public/geo_routes/:id/:filename', path: ':rails_root:url'
  validates_attachment_content_type :geo_route, content_type: ['application/xml', 'application/octet-stream']
  validates_attachment_file_name :geo_route, matches: [/gpx\Z/, /tcx\Z/]

  after_save :update_route, if: ->(obj) { obj.geo_route_processed == false && obj.geo_route.present? }
  scope :started_at, -> { order('started_at DESC') }

  class << self
    def group_mileage_by_month
      unscoped
        .group_by_month(:started_at, format: '%B %Y')
        .sum(:total_distance)
        .map { |m| { m[0] => (m[1] * 0.000621371).round(2) }.flatten }
    end

    def find_by_period(period = Time.now.all_year)
      where(started_at: period)
    end

    def sum_distance
      sum(:total_distance) * 0.000621371
    end

    def sum_elevation_gain
      sum(:total_elevation_gain) * 3.28084
    end

    def sum_time
      time = sum(:total_time)
      seconds = time % 60
      minutes = (time / 60) % 60
      hours = time / 3600
      "#{hours} hrs, #{minutes} mins, #{seconds} secs"
    end

    def average_heart_rate
      average(:average_heart_rate)
    end

    def sum_calories
      sum(:total_calories)
    end
  end

  private

  def update_route
    UpdateGeoRouteService.new.execute(id)
  end
end

app/models/geo_point.rb
class GeoPoint < ActiveRecord::Base
  belongs_to :activity

  class << self
    def lat_lng
      order('time ASC')
        .pluck(:lat, :lng)
        .reject { |point| point.any?(&:blank?) }
        .map { |point| { lat: point[0].to_f, lng: point[1].to_f } }
        .uniq
    end

    def heart_rate
      pluck(:time, :heart_rate)
        .reject { |point| point.any?(&:blank?) }
        .map { |point| { point[0] => point[1] }.flatten }
        .uniq
    end

    def heart_rate_intensity
      points = pluck(:heart_rate).reject(&:blank?)
      count = points.count

      points
        .group_by { |x| x / 10 }
        .sort
        .map { |k, vs| { ((10 * k)..(10 * k + 10)) => ((vs.count.to_f / count.to_f) * 100.0).round(2) }.flatten }
    end

    def elevation
      pluck(:time, :elevation)
        .reject { |point| point.any?(&:blank?) }
        .map { |point| { point[0] => (point[1] * 3.28084).round(2) }.flatten }
        .uniq
    end

    def speed
      pluck(:time, :speed)
        .reject { |point| point.any?(&:blank?) }
        .map { |point| { point[0] => (point[1] * 2.23694).round(2) }.flatten }
        .uniq
    end
  end
end

app/models/lap.rb
class Lap < ActiveRecord::Base
  belongs_to :activity

  scope :started_at, -> { order('start_time ASC') }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.started_at.page(params[:page])
    @lifetime = Activity.all
    @last_year = Activity.find_by_period(Time.zone.now.all_year)
    @last_month = Activity.find_by_period(Time.zone.now.all_month)
    @last_week = Activity.find_by_period(Time.zone.now.all_week)
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def mileage
    render json: Activity.group_mileage_by_month
  end

  def heart_rate
    render json: Activity.find(params[:id]).geo_points.heart_rate
  end

  def heart_rate_intensity
    render json: Activity.find(params[:id]).geo_points.heart_rate_intensity
  end

  def elevation
    render json: Activity.find(params[:id]).geo_points.elevation
  end

  def speed
    render json: Activity.find(params[:id]).geo_points.speed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Second Wind'
    return base_title if page_title.empty?
    "#{base_title} | #{page_title}"
  end
end

app/views/activities/_activity.html.haml
- activities.each do |activity|
  - activity_presenter = ActivityPresenter.new(activity)
  %tr
    %td= link_to activity_presenter.started_at, activity_path(activity)
    %td= activity.sport
    %td
      %i{ class: "pull-left glyphicon glyphicon-arrow-#{activity_presenter.trend}" }
    %td= activity_presenter.total_distance
    %td= activity_presenter.elapsed_time
    %td= activity_presenter.total_calories
    %td= activity_presenter.average_speed
    %td= activity_presenter.average_pace
    %td= activity_presenter.average_cadence
    %td= activity_presenter.maximum_cadence
    %td= activity_presenter.total_elevation_gain
    %td= activity_presenter.total_elevation_loss
    %td= activity_presenter.max_elevation
    %td= activity_presenter.max_heart_rate
    %td= activity_presenter.average_heart_rate

app/views/activities/_lap.html.haml
- activity.laps.started_at.each_with_index do |lap, index|
  - lap_presenter = LapPresenter.new(lap)
  %tr
    %td= index + 1
    %td= lap_presenter.elapsed_time
    %td= lap_presenter.total_distance
    %td= lap_presenter.average_speed

app/views/activities/_show_laps_table.html.haml
%h2 Laps
%table.table.table-striped
  %thead
    %tr
      %th
      %th Time
      %th Distance
      %th Average Speed
  %tbody#laps
    = render partial: 'lap', locals: { activity: activity }

app/views/activities/_show_summary_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th{ colspan: 3 } Totals
      %th{ colspan: 2 } Speed
      %th{ colspan: 2 } Pace
      %th{ colspan: 2 } Cadence
      %th{ colspan: 4 } Elevation
      %th{ colspan: 3 } Heart Rate
    %tr
      %th Distance
      %th Time
      %th Calories
      %th Average
      %th Max
      %th Average
      %th Max
      %th Average
      %th Max
      %th Gain
      %th Loss
      %th Max
      %th Min
      %th Average
      %th Max
      %th Min
  %tbody
    %tr
      %td= activity_presenter.total_distance
      %td= activity_presenter.elapsed_time
      %td= activity_presenter.total_calories
      %td= activity_presenter.average_speed
      %td= activity_presenter.max_speed
      %td= activity_presenter.average_pace
      %td= activity_presenter.max_pace
      %td= activity_presenter.average_cadence
      %td= activity_presenter.maximum_cadence
      %td= activity_presenter.total_elevation_gain
      %td= activity_presenter.total_elevation_loss
      %td= activity_presenter.max_elevation
      %td= activity_presenter.min_elevation
      %td= activity_presenter.average_heart_rate
      %td= activity_presenter.max_heart_rate
      %td= activity_presenter.min_heart_rate

app/views/activities/_show_tabs_content.html.haml
.tab-content
  .tab-pane.active#map-tab
    .map-container#map-container
      .map#map
  .tab-pane#summary-profiles-tab
    .col-lg-12
      %br
      = area_chart heart_rate_path, 'library' => { 'yAxis' => { 'title' => { 'text' => 'Heart Rate (bpm)' } }, 'title' => { 'text' => 'Heart Rate' }, 'colors' => ['#990000'] }
      %br
      = area_chart elevation_path, 'library' => { 'yAxis' => { 'title' => { 'text' => 'Elevation (ft)' } }, 'title' => { 'text' => 'Elevation' }, 'colors' => ['#228400'] }
      %br
      = area_chart speed_path, 'library' => { 'yAxis' => { 'title' => { 'text' => 'Speed (mph)' } }, 'title' => { 'text' => 'Speed' }, 'colors' => ['#0077e6'] }
  .tab-pane#summary-intensity-tab
    .col-lg-12
      %br
      = column_chart heart_rate_intensity_path, 'library' => { 'yAxis' => { 'title' => { 'text' => 'Percent of Time' }, 'labels' => { 'format' => '{value} %' } }, 'title' => { 'text' => 'Percent of Time Spent at Heart Rates' }, 'colors' => ['#990000'] }

:javascript
  $(document).ready(function() {
    gmaps_draw_route(#{activity.geo_points.lat_lng.to_json});

    $(document).on("click", "#map-nav-tab", function() {
      google.maps.event.trigger(map, "resize");
    });

    $(document).on("click", "#summary-profiles-nav-tab", function() {
      var chartIds = ["#chart-1", "#chart-2", "#chart-3"];

      chartIds.forEach(function(id) {
        var height = $(id).height();
        var width = $(id).width();
        $(id).highcharts().setSize(width, height, doAnimation = false);
      });
    });

    $(document).on("click", "#summary-intensity-nav-tab", function() {
      var height = $("#chart-4").height();
      var width = $("#chart-4").width();
      $("#chart-4").highcharts().setSize(width, height, doAnimation = false);
    });
  });

app/views/activities/_show_tabs_nav.html.haml
%ul.nav.nav-tabs
  %li.active{ role: 'presentation' }
    %a#map-nav-tab{ 'data-toggle' => 'tab', :href => '#map-tab', :role => 'tab' }
      %i.glyphicon.glyphicon-map-marker.pull-left
      &nbsp; Map
  %li{ role: 'presentation' }
    %a#summary-profiles-nav-tab{ 'data-toggle' => 'tab', :href => '#summary-profiles-tab', :role => 'tab' }
      %i.glyphicon.glyphicon-stats.pull-left
      &nbsp; Profiles
  %li{ role: 'presentation' }
    %a#summary-intensity-nav-tab{ 'data-toggle' => 'tab', :href => '#summary-intensity-tab', :role => 'tab' }
      %i.glyphicon.glyphicon-signal.pull-left
      &nbsp; Heart Rate Intensity

app/views/activities/_summary.html.haml
%table.table.table-striped
  %thead
    %tr
      %th
      %th Activities
      %th Calories
      %th Distance
      %th Time
      %th Elevation Gain
      %th Average Heart Rate
  %tbody
    %tr
      %td This Week
      = render partial: 'summary_data', locals: { activities: last_week }
    %tr
      %td This Month
      = render partial: 'summary_data', locals: { activities: last_month }
    %tr
      %td This Year
      = render partial: 'summary_data', locals: { activities: last_year }
    %tr
      %td Lifetime
      = render partial: 'summary_data', locals: { activities: lifetime }

app/views/activities/_summary_data.html.haml
%td= activities.count
%td= "#{number_with_delimiter(activities.sum_calories)}"
%td= "#{number_with_precision(activities.sum_distance, precision: 2, delimiter: ',')} miles"
%td= activities.sum_time
%td= "#{number_with_precision(activities.sum_elevation_gain, precision: 2, delimiter: ',')} ft"
%td= "#{number_with_precision(activities.average_heart_rate, precision: 0)} bpm"

app/views/activities/_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th{ rowspan: 2 } Started At
      %th{ rowspan: 2 } Type
      %th{ rowspan: 2 } Trend
      %th{ colspan: 3 } Totals
      %th{ colspan: 2 } Timing
      %th{ colspan: 2 } Cadence
      %th{ colspan: 3 } Elevation
      %th{ colspan: 2 } Heart Rate
    %tr
      %th Distance
      %th Time
      %th Calories
      %th Average Speed
      %th Average Pace
      %th Average
      %th Max
      %th Gain
      %th Loss
      %th Max
      %th Max
      %th Average
  %tbody#activities
    = render partial: 'activity', locals: { activities: activities }

#paginator
  = paginate activities, remote: true

app/views/activities/_tabs_content_activities.html.haml
%ul.nav.nav-pills
  %li.active{ role: 'presentation' }
    %a#table-tab-link{ 'data-toggle' => 'tab', :href => '#table-tab', :role => 'tab' } Activities
  %li{ role: 'presentation' }
    %a#summary-tab-link{ 'data-toggle' => 'tab', :href => '#summaries-tab', :role => 'tab' } Summary
.tab-content
  .tab-pane.active#table-tab
    = render partial: 'table', locals: { activities: activities }
  .tab-pane#summaries-tab
    = render partial: 'summary', locals: { lifetime: lifetime, last_year: last_year, last_month: last_month, last_week: last_week }

app/views/activities/_tabs_nav.html.haml
%ul.nav.nav-tabs
  %li.active{ role: 'presentation' }
    %a#activities-nav-tab{ 'data-toggle' => 'tab', :href => '#activities-tab', :role => 'tab' }
      %i.glyphicon.glyphicon-list.pull-left
      &nbsp; Activities
  %li{ role: 'presentation' }
    %a#charts-nav-tab{ 'data-toggle' => 'tab', :href => '#charts-tab', :role => 'tab' }
      %i.glyphicon.glyphicon-stats.pull-left
      &nbsp; Charts

app/views/activities/index.html.haml
= javascript_include_tag 'highcharts', 'chartkick'

- provide(:title, 'Activities')

%h1 Activities

.row
  - if @activities.any?
    = render partial: 'tabs_nav'
    = render partial: 'tabs_content', locals: { activities: @activities, lifetime: @lifetime, last_year: @last_year, last_month: @last_month, last_week: @last_week }

app/views/activities/index.js.haml
$('#activities').html('#{escape_javascript (render partial: 'activity', locals: { activities: @activities } )}');
$('#paginator').html('#{escape_javascript(paginate(@activities, remote: true).to_s)}');

app/views/activities/show.html.haml
%script{ src: '//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry', type: 'text/javascript' }
%script{ src: '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js', type: 'text/javascript' }

= javascript_include_tag 'highcharts', 'chartkick'

- activity_presenter = ActivityPresenter.new(@activity)

- provide(:title, "#{activity_presenter.started_at_long}")

%h1= "#{activity_presenter.started_at_long}"
%h2= "#{activity_presenter.total_distance} around #{activity_presenter.where}"

= render partial: 'show_summary_table', locals: { activity: @activity, activity_presenter: activity_presenter }

.row
  .col-lg-4
    = render partial: 'show_laps_table', locals: { activity: @activity }
  .col-lg-8
    = render partial: 'show_tabs_nav'
    = render partial: 'show_tabs_content', locals: { activity: @activity, activity_presenter: activity_presenter }

app/views/layouts/_footer.html.haml
%footer.footer

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-default.navbar-fixed-top
    .navbar-inner
      .container
        = link_to 'Second Wind', root_path, class: 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key,value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
    = render 'layouts/footer'

app/views/shared/_activity_error_messages.html.haml
- if @activity.errors.any?
  .error_explanation
    %ul
      - @activity.errors.full_messages.each do |msg|
        %li
          * #{msg}